server:
  port: 8071
spring:
  application:
    name: validarproducto
  datasource:
    password: 12345
    url: jdbc:postgresql://postgreslibapp:5432/validarproducto
    username: krojasco
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://zipkinlibapp:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-libapp:8075/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false