services:
  postgres:
    container_name: postgreslibapp
    image: postgres
    environment:
      POSTGRES_USER: krojasco
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5430:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadminlibapp
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5030:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkinlibapp
    ports:
      - "9415:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    container_name: rabbitmqlibapp
    ports:
      - "5675:5672"
      - "15675:15672"
    networks:
      - spring
#  eureka-server:
#    image: karcxcoding/mod-eureka-server:latest
#    container_name: eureka-server-libapp
#    ports:
#      - "8075:8075"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#  apigateway:
#    image: karcxcoding/mod-apigateway:latest
#    container_name: apigateway-libapp
#    ports:
#      - "8074:8074"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
  producto:
    image: karcxcoding/mod-producto:latest
    container_name: producto-libapp
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - eureka-server
  validarproducto:
    image: karcxcoding/mod-validarproducto:latest
    container_name: validarproducto-libapp
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - eureka-server
  notificacion:
    image: karcxcoding/mod-notificacion:latest
    container_name: notificacion-libapp
    ports:
      - "8072:8072"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - eureka-server

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
