services:
  postgres:
    container_name: postgreslibapp
    image: postgres
    environment:
      POSTGRES_USER: krojasco
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5430:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadminlibapp
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5030:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkinlibapp
    ports:
      - "9415:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    container_name: rabbitmqlibapp
    ports:
      - "5675:5672"
      - "15675:15672"
    networks:
      - spring

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
