server:
  port: 8072
spring:
  application:
    name: notificacion
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5430/notificacion
    username: krojasco
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://localhost:9415
  rabbitmq:
    addresses: localhost:5675
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8075/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notificacion.queue
  routing-keys:
    internal-notification: internal.notification.routing-key