server:
  port: 8072
spring:
  application:
    name: notificacion
  datasource:
    password: 12345
    url: jdbc:postgresql://postgreslibapp:5432/notificacion
    username: krojasco
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://zipkinlibapp:9411
  rabbitmq:
    addresses: rabbitmqlibapp:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-libapp:8075/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notificacion.queue
  routing-keys:
    internal-notification: internal.notification.routing-key