server:
  port: 8050
spring:
  datasource:
    password: 12345
    url: jdbc:postgresql://postgreslibapp:5432/autenticacion
    username: libreapp
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://zipkinlibapp:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-libapp:8075/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false

jwt:
  secret: secret

admin-paths:
  paths:
    - uri: "/api/v1/product"
      method: "POST"
    - uri: "/api/v1/product"
      method: "PUT"
    - uri: "/api/v1/product/{1}[1-9]+[0-9]*"
      method: "DELETE"
    - uri: "/api/v1/product-check/{1}[1-9]+[0-9]*"
      method: "GET"