server:
  port: 8070
spring:
  application:
    name: producto
  datasource:
    password: 12345
    url: jdbc:postgresql://postgreslibapp:5432/producto
    username: libreapp
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
      schema-locations: classpath:bd/tablas.sql
      data-locations: classpath:bd/data.sql
  zipkin:
    base-url: http://zipkinlibapp:9411
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-libapp:8075/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      validatelibroCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    retry-aspect-order: 2
    instances:
      validatelibroRetry:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 5s