server:
  port: 8070
spring:
  application:
    name: producto
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5430/producto
    username: krojasco
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
      schema-locations: classpath:bd/tablas.sql
      data-locations: classpath:bd/data.sql
  zipkin:
    base-url: http://localhost:9415
  rabbitmq:
    addresses: localhost:5675
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8075/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false