server:
  port: 8070
spring:
  application:
    name: producto
  datasource:
    password: 12345
    url: jdbc:postgresql://postgreslibapp:5432/producto
    username: krojasco
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:bd/tablas.sql
#      data-locations: classpath:bd/reback_data.sql
  zipkin:
    base-url: http://zipkinlibapp:9411
  rabbitmq:
    addresses: rabbitmqlibapp:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-libapp:8075/eureka
    fetch-registry: true
    register-with-eureka: true