server:
  port: 8074

spring:
  zipkin:
    base-url: http://zipkinlibapp:9411
  cloud:
    gateway:
      routes:
        - id: producto
          uri: lb://PRODUCTO
          predicates:
            - Path=/api/v1/product/**
          filters:
            - AutorizacionFilter
        - id: producto
          uri: lb://PRODUCTO
          predicates:
            - Path=/api/v1/author/**
          filters:
            - AutorizacionFilter
        - id: producto
          uri: lb://PRODUCTO
          predicates:
            - Path=/api/v1/category/**
          filters:
            - AutorizacionFilter
        - id: validarproducto
          uri: lb://VALIDARPRODUCTO
          predicates:
            - Path=/api/v1/product-check/**
          filters:
            - AutorizacionFilter
        - id: validarproducto
          uri: lb://VALIDARPRODUCTO
          predicates:
            - Path=/api/v1/product-check/**
          filters:
            - AutorizacionFilter
        - id: autenticacion
          uri: lb://AUTENTICACION
          predicates:
            - Path=/api/v1/autenticacion/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-libapp:8075/eureka
    fetch-registry: true
    register-with-eureka: true