server:
  port: 8060
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Karc-coding/MicroServicios-ModLibreApp
          search-paths: config-data/default