spring:
  application:
    name: notificacionkafka
  config:
    import: "optional:configserver:http://config-server:8060"
  cloud:
    config:
      enabled: true
      uri: http://config-server:8060